local _G, setmetatable                   = _G, setmetatable
local TMW                                = TMW
local CNDT                               = TMW.CNDT
local Env                                = CNDT.Env
local Action                             = Action
local CONST                              = Action.CONST
local Listener                           = Action.Listener
local Create                             = Action.Create
local GetToggle                          = Action.GetToggle
local GetState                           = Action.GetState
local GetGCD                             = Action.GetGCD
local BurstIsOn                          = Action.BurstIsOn
local EnemyTeam                          = Action.EnemyTeam
local FriendlyTeam                       = Action.FriendlyTeam
local LoC                                = Action.LoC
local Player                             = Action.Player
local Pet                                = LibStub("PetLibary")
local MultiUnits                         = Action.MultiUnits
local UnitCooldown                       = Action.UnitCooldown
local Unit                               = Action.Unit
local IsUnitEnemy                        = Action.IsUnitEnemy
local IsUnitFriendly                     = Action.IsUnitFriendly
local ActiveUnitPlates                   = MultiUnits:GetActiveUnitPlates()
local IsIndoors, UnitIsUnit              = IsIndoors, UnitIsUnit
local pairs                              = pairs
local ACTION_CONST_WARRIOR_ARMS          = CONST.WARRIOR_ARMS
local ACTION_CONST_SPELLID_FREEZING_TRAP = CONST.SPELLID_FREEZING_TRAP

